### ISSUE TITLE
incompatable cmake version

### ISSUE THREAD

**Issue by vullob** [rkumar0322/a1part2#3]
Hey!

When running cmake . inside the docker image specified for A2 I get this error.
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.15 or higher is required.  You are running version 3.10.2


-- Configuring incomplete, errors occurred!
```

It looks like the version target specified in [yourCMakeLists.txt](https://github.com/rkumar0322/a1part2/blob/890d0a3605fc7cd908ca88a8bdebdf482404330c/CMakeLists.txt#L1) is the root of this issue.

Can this be changed so we can run your tests against our code?

Thanks,
- Brian

**Comment by Xinhan-Yan** [comment]
Sorry for the late reply.

Our code is in part2 directory so I don't think this text file matters. We will remove files other than part2 in the end. 

Besides, we just changed our APIs to support types of int, float and bool. Let me know if you have any questions.
